<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Villas' => 'Villalar',
	'Adult' => 'Yetişkin',
	'Child' => 'Çocuk',
	'Check out date' => 'Çıkış tarihi',
	'Check in date' => 'Giriş tarihi',
	'Villa name' => 'Villa adı',
	'About Us' => 'Hakkımızda',
	'Contact' => 'İletişim',
	'Tourism Butterfly' => 'Türizm Kelebeği',
	'Villa Owners' => 'Villa Sahipleri',
	'contact' => 'iletisim',
	'dd/mm/yyyy' => 'gg/aa/yyyy',
	'Filters' => 'Villa özellikleri',
	'Price range' => 'Fiyat aralığı',
	'Villas starting at' => 'Villa bulundu',
	'Search' => 'Ara',
	'Narrow results or' => 'Seçenek ekleyin veya',
	'view all' => 'hepsini görün',
	'Region' => 'Bölge',
	'Villa Preferences' => 'Villa Özellikleri',
	'Floors' => 'Kat Sayısı',
	'Private villa' => 'Müstakil villa',
	'Inside site' => 'Site İçerisinde',
	'Private pool' => 'Müstakil Havuzlu',
	'Shared pool' => 'Ortak Havuzlu',
	'Heated pool' => 'Isıtmalı Havuz',
	'Closed pool' => 'Kapalı Havuz',
	'Nature secured' => 'Doğal Korunaklı',
	'Curtain secured' => 'Perdeli Korunaklı',
	'Sea view' => 'Deniz Manzarası',
	'Nature view' => 'Doğa Manzarası',
	'Private park' => 'Özel Otopark',
	'Shared park' => 'Ortak Otopark',
	'Pet' => 'Evcil hayvan',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
];
